name: Unit-tests for Pip install

on:
  pull_request:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        cuda_arch_version: ["12.1"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.4xlarge.nvidia.gpu
      repository: pytorch/captum
      gpu-arch-type: cuda
      gpu-arch-version: ${{ matrix.cuda_arch_version }}
      script: |
        python3 -m pip install --upgrade pip --progress-bar off
        python3 -m pip install -e .[dev] --progress-bar off

        # Build package
        python3 -m pip install build --progress-bar off
        python3 -m build

        # Run Tests
        python3 -m pytest -ra --cov=. --cov-report term-missing
