name: Test deployment

on:
  pull_request:
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup / build docs
        run: |
          sudo chmod -R 777 .
          python3 -m pip install --upgrade pip --progress-bar off
          python3 -m pip install -e .[dev] --progress-bar off
          python3 -m pip install beautifulsoup4 ipython jinja2==3.0.0 nbconvert==5.6.1 ipython_genutils --progress-bar off
          ./scripts/build_docs.sh -b
          cd website
